### ISSUE TITLE
[BUG]  Issue when download helm package file - https://mirror.openshift.com/pub/openshift-v4/clients/helm/3.14.4/sha256sum.txt

### ISSUE THREAD

**Issue by lukaszkregielsanofi** [redhat-actions/openshift-tools-installer#113]
We uses the fallowing piece of code as part of our workflow:

```
    - uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: "4"
        helm: "latest"
```
And from yesterday workflow is failling with the fallowing error:
` Error: Did not find file "helm-linux-amd64.tar.gz" in the given hash file `
From simple investigation I see that https://mirror.openshift.com/pub/openshift-v4/clients/helm/3.14.4/helm-linux-amd64.tar.gz redirects to https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/helm/3.14.4/helm-linux-amd64.tar.gz and works perectly, but second file - https://mirror.openshift.com/pub/openshift-v4/clients/helm/3.14.4/sha256sum.txt does not have redirerection and it gives 404 not found what finally finish workflow with an (above) error.

I guess that for some period of time we were using helm-linux-amd64.tar.gz along and/or sha256sum.txt from cache as we use cache, so change was done recently and it does not mean it was changed yesterday.

**Comment by michael-valdron** [comment]
Running into the same issue here on the devfile registry when downloading `odo` tool for our testing: https://github.com/devfile/api/issues/1656#issue-2729026225

**Comment by MohammedDhange** [comment]
Running into the same error, The hash file does seem to be redirecting to https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/helm/3.14.4/sha256sum.txt but despite that we're getting `Error: Did not find file "helm-linux-amd64.tar.gz" in the given hash file`.
What's annoying is that when I manually download the file and check, it contains `linux-amd64.tar.gz`, so I'm at a loss for what to do.
```
29b02f85d8094ae672133bfdaae1271c6c6b238654f149cfbac8e408b4d1acce  helm-darwin-amd64
c9433254487b52e766a2aeb7a350fabdee993bcf7da246f6dd481c43a7f5a664  helm-darwin-amd64.tar.gz
bca5b1567f8375957ed3122d13b2385e6b2c1c9080daf918fed315d6179bc19f  helm-darwin-arm64
4f5e583f16bf0696420c982faaab28e5acb270b911a6de09dad623805a619509  helm-darwin-arm64.tar.gz
9860314e4e67bc72158b6c95290dc21d1e68dceedcc68136b54a223da8703844  helm-linux-amd64
c56e8af7ded729208c2af3f26351535ad12da1d730469c465fc117f6827037eb  helm-linux-amd64.tar.gz
73b089f1272b2b5a1977596a07617756fcf3c45028a1875e277cfbb7c09a89ea  helm-linux-arm64
2a3ea49a25c73ad4ed352e62f817b1d75bce36bbbd4209c69ad034adc6211cee  helm-linux-arm64.tar.gz
641ef324176db7b0ccb0c2a7bfebc6e5370e892d1028e7ebadfc9664fefbfa38  helm-linux-ppc64le
1a5f8c1c55a17510074fe3e97fba7b5a7c0c8740e337db3b3d2847ce68797d8e  helm-linux-ppc64le.tar.gz
2be564a9a5906743ef1b12db8972dd04a8ef5c75418ac8e034f1c10c88e2aa35  helm-linux-s390x
903ec7ff94efa75e5e020569cb9551ba41843df65e1fd1dd166cb4dca5496cd1  helm-linux-s390x.tar.gz
08a94200f9ea1b22f3a161dd7e2b6516dab514879a1706e44e7243d2603fa717  helm-windows-amd64.exe
078b561483f977e191748f475e4a5fbd98f527f7dc3b3f2ccfb343707c7831e1  helm-windows-amd64.exe.zip
```

**Comment by komish** [comment]
This should be fixed. There was a broken redirect at the CDN. Let us know if you see further issues.
EDIT: @MohammedDhange Let me see if I can replicate.

**Comment by komish** [comment]
@MohammedDhange the tools installer seems to be working fine here. Can you create a **new issue** with your details? I think this issue is okay to close for the moment.

(note: I don't have close permissions, just helping chase this down)

**Comment by michael-valdron** [comment]
> This should be fixed. There was a broken redirect at the CDN. Let us know if you see further issues. EDIT: @MohammedDhange Let me see if I can replicate.

Confirmed on my end it works now:
```
$ curl -OL https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/v3.15.0/sha256sum.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1214  100  1214    0     0   2489      0 --:--:-- --:--:-- --:--:--  2489
```

**Comment by MohammedDhange** [comment]
@komish @michael-valdron Can confirm its working for me as well. Thanks!

**Comment by lukaszkregielsanofi** [comment]
It works for me as well. For me - we can close that issue. Thank you @komish
