### ISSUE TITLE
Download cli binaries through CDN instead of mirror.openshift.com

### ISSUE THREAD

**Issue by Divyansh42** [redhat-actions/openshift-tools-installer#14]
In this action we are using mirror.openshift.com to download binaries, but as binaries will be releasing through CDN instead of mirror.openshift.com in future.
So we will have to refactor the code to download binaries from CDN.

This change should be done once we have all the binaries moved to CDN.

**Comment by tetchel** [comment]
blocked on this CDN actually existing.

**Comment by deboer-tim** [comment]
Some binaries are now on CDN, e.g. CRC 1.27. I'm not sure if this is universal, but there is a redirect setup from mirror and no plans to remove the mirror listing. If this remains true, nothing needs change on the client side and this could be closed.

**Comment by tetchel** [comment]
So long as the redirect is in place, we're golden!
