### ISSUE TITLE
[BUG] CRC failing on macOS with the latest (1.28.0) release

### ISSUE THREAD

**Issue by Divyansh42** [redhat-actions/openshift-tools-installer#39]
With the update of [latest](https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.28.0/) version, crc worflow is failing.
As in the latest release, there is no `.tar.gz` file.
It has only `.pkg` file and this action doesn't support this format as of now

**Comment by tetchel** [comment]
https://github.com/redhat-actions/openshift-tools-installer/blob/main/src/util/unzip.ts#L8
