### ISSUE TITLE
Windows build of kustomize is temporarily disabled for v4.2.0

### ISSUE THREAD

**Issue by divyansh42** [redhat-actions/openshift-tools-installer#42]
Related to https://github.com/kubernetes-sigs/kustomize/issues/4028
Nightly job failing: https://github.com/redhat-actions/openshift-tools-installer/runs/2968042687?check_suite_focus=true#step:3:101

**Comment by tetchel** [comment]
I checked 4.3.0 and it's still missing.

**Comment by divyansh42** [comment]
Windows build is reenabled in `4.4.1`
https://github.com/kubernetes-sigs/kustomize/issues/4028
