### ISSUE TITLE
All the tags are not fetched in the github for the provided tool

### ISSUE THREAD

**Issue by Divyansh42** [redhat-actions/openshift-tools-installer#43]
Presently, only 30 tags are fetched from GitHub APIs by default.
![image](https://user-images.githubusercontent.com/25487826/124811236-de660280-df7f-11eb-881c-5593e513507d.png)

To make this action work in all the cases, ideally, we'd have to run through all the pages that are fetched by the API.

**Comment by tetchel** [comment]
good catch! 

In the connector, I am using https://github.com/octokit/plugin-paginate-rest.js/ to do the pagination. You can use it to wrap an octokit and paginate easily. 

it may not work with the @actions octokit, though.
