### ISSUE TITLE
[FEATURE] add kubectl

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-actions/openshift-tools-installer#48]
### Is your feature request related to a problem? Please describe.

Can you add support for `kubectl` too? Some tools rely on kubectl.

### Describe the solution you'd like

Add install and cache for kubectl

### Describe alternatives you've considered

azure/setup-kubectl

**Comment by tetchel** [comment]
There are no kubectl binaries on GitHub so this is out of scope of this action.

However when installing `oc`, `kubectl` is also installed. But then you get whichever kubectl/k8s version that version of oc/ocp corresponds to, rather than being able to pick a kubectl/k8s version.
