### ISSUE TITLE
[BUG] Not able to install tools from OpenShift Mirror

### ISSUE THREAD

**Issue by divyansh42** [redhat-actions/openshift-tools-installer#58]
All the nightly checks are failing as none of the tools can be installed from the OpenShift Mirror.
We are investigating this problem and will update here as soon as we fix the bug.

**Comment by divyansh42** [comment]
If your use case satisfies, please feel free to use input `source: github` to download and install binaries from GitHub instead of OpenShift Mirror.

**Comment by tetchel** [comment]
it looks like there's been a redirect added: 

```
curl -i https://mirror.openshift.com/pub/openshift-v4/clients/serverless/0.15.2
HTTP/2 302
content-type: application/xml
content-length: 0
date: Thu, 16 Dec 2021 01:07:44 GMT
server: AmazonS3
location: /pub/openshift-v4/x86_64/clients/serverless/0.15.2/
x-cache: Hit from cloudfront
via: 1.1 50faaaa196a6b0875217ef7827f97d7c.cloudfront.net (CloudFront)
x-amz-cf-pop: SEA19-C3
x-amz-cf-id: IjSgDyxzZbDbKEjIhRkSiU33zm1IwdFhHkfqk2OFOD1KPlNZ8Ae6aw==
age: 12813
```

if I add the `-L` flag (which follows redirects) then it works

**Comment by tetchel** [comment]
If you browse the mirror it's also received a facelift so I suppose now they've moved to the new mirror we were warned about

**Comment by urswiss** [comment]
`source: github` is not working for us:

![image](https://user-images.githubusercontent.com/19600534/146346028-a3da239f-0652-4801-bde3-4c94547b1c16.png)

**Comment by milindkejriwal** [comment]
oc and helm are not available on source: github :face_with_head_bandage:

**Comment by divyansh42** [comment]
Yes, you can find the list of tools that are available on GitHub in the following list https://github.com/redhat-actions/openshift-tools-installer#supported-tools.

**Comment by divyansh42** [comment]
@tetchel I noticed a strange thing if you put `/` at the end of the URL. Then everything works fine.
```
curl -i https://mirror.openshift.com/pub/openshift-v4/clients/serverless/0.15.2/ 
HTTP/2 200 
content-type: text/html
content-length: 13967
server: CloudFront
date: Thu, 16 Dec 2021 07:27:53 GMT
vary: Accept-Encoding
cache-control: max-age=0
x-cache: LambdaGeneratedResponse from cloudfront
via: 1.1 5e51c2cb85f3832b4e4037f8dff6904d.cloudfront.net (CloudFront)
x-amz-cf-pop: TLV50-C2
x-amz-cf-id: 6pEogNMCl23rE28YVp5bT2hyGjPsL7K9jF-4LEv8a-7289ifeYG5Dw==
```
I think this solution will work for us.

But ideally, I don't think this should happen as the OpenShift Mirror team told us that transition won't be a breaking change.

**Comment by divyansh42** [comment]
We are working on a fix for this. Hopefully, by the end of the day, we'll come up with the patch.

**Comment by divyansh42** [comment]
@urswiss We have fixed this issue, could you please re-run your workflows and confirm.

**Comment by urswiss** [comment]
@divyansh42 I can confirm that it is working again. Thanks for fixing this!
However, the action redhat-actions/openshift-tools-installer@v1 runs about 3 minutes now, compared to < 20 seconds yesterday.

**Comment by divyansh42** [comment]
@urswiss I am wondering if caching is the case here. With the updated OpenShift mirror, probably older cached versioned is not matched with the new version, hence it has to download the binaries once again.
Could you please re-run the workflow to check the time difference?

**Comment by milindkejriwal** [comment]
Thanks a lot for getting on top of this!

**Comment by urswiss** [comment]
@divyansh42 I ran it a couple of times now, and it's always around 3 minutes. But I can't rule out that it is something on our end (we have a Openshift inside the company). We will monitor the situation in the next few days.

**Current situation** (3 minutes)

![image](https://user-images.githubusercontent.com/19600534/146411650-2517c92e-005e-462d-ba53-4a04735e7162.png)

**Yesterday morning** (17 seconds)

![image](https://user-images.githubusercontent.com/19600534/146411831-68b052a1-5d5c-40b0-af25-ecff6612748b.png)

**Comment by divyansh42** [comment]
@urswiss You are running on GitHub enterprise, so cache can't be a reason for this time difference.
We'll also try to investigate this on our end.

**Comment by jduimovich** [comment]
As a data point, I ran a bare bones install in this test repo https://github.com/jduimovich/bench-install which installed oc on github in cached and not-cached modes.  Both run in small numbers of seconds. 

This is the uncached run (5s) and the cached (not shown) is in 2s. 
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/7844190/146419337-348bfbd8-edc3-4121-9a83-d0cb9e609584.png">

**Comment by divyansh42** [comment]
Resolved in https://github.com/redhat-actions/openshift-tools-installer/pull/59
