### ISSUE TITLE
Tools installation from mirror fails with 404

### ISSUE THREAD

**Issue by divyansh42** [redhat-actions/openshift-tools-installer#61]
From today, this action is not able to install tools from the mirror. It fails with the error https://github.com/redhat-actions/openshift-tools-installer/runs/4770519749?check_suite_focus=true#step:3:61

We'll update here once we get more details on this issue.

**Comment by sveneh** [comment]
Three weeks after https://github.com/redhat-actions/openshift-tools-installer/issues/58, we have the same problem again?

**Comment by divyansh42** [comment]
Please try to re-run your workflows.

There was a web application firewall in OpenShift Mirror which was enabled yesterday and that was creating all these problems.
We have fixed that and you should be able to run your workflows now.
Thanks for your co-operation and patience. :pray:

**Comment by urswiss** [comment]
is it - for github enterprise - now as fast as it used to be before the first incident in December?
