### ISSUE TITLE
[BUG] outdated odo location 

### ISSUE THREAD

**Issue by kadel** [redhat-actions/openshift-tools-installer#66]
### Describe the bug

This action installed an outdated odo version.

New odo versions are published at https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/ 

location on mirror.openshift.com is no longer updated

**Comment by divyansh42** [comment]
Thanks for reporting this. We'll take a look at this.

**Comment by rtaniwa** [comment]
Thanks Divyanshu. Hopefully this immediate change is pretty straightforward, but it does prompt another question. Do we have a good process in place for how we keep the tools we install current with their releases?

**Comment by josephca** [comment]
@divyansh42 - any plan to address this issue soon?  Thanks!

**Comment by divyansh42** [comment]
@josephca I am waiting for this [issue](https://github.com/redhat-developer/odo/issues/5474) to be solved first. If they redirect then we are in a very good state, otherwise we'll decide what changes need to be done in this action.

**Comment by kadel** [comment]
Please don't wait for that. We don't know if redirecting will be possible. But even if we are able to set it up odo should get downloaded from the primary location.

**Comment by divyansh42** [comment]
Actually this action is made to install tools from the mirror. So, we followed a very generalised way and made it to work only for OpenShift Mirror. Therefore there is only one logic that works for all the tools. To install odo from different location we will have to re-think and re-design this odo usecase seperately.
I will consult this with the team and update here.
