### ISSUE TITLE
[BUG] redhat-actions/openshift-tools-installer using deprecated version of Node.js

### ISSUE THREAD

**Issue by nsalfos** [redhat-actions/openshift-tools-installer#88]
### Version
redhat-actions/openshift-tools-installer@v1.10

### Describe the bug

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: redhat-actions/openshift-tools-installer, redhat-actions/oc-login
`
### Steps to reproduce, workflow links, screenshots

Any attempt to use the actions should show this warning. 
I already reported in 2 other actions that apparently also used deprecated versions of Node.js. [here](https://github.com/tj-actions/changed-files/issues/678) & [here](https://github.com/mxschmitt/action-tmate/issues/139)

**Comment by oestoer** [comment]
Release https://github.com/redhat-actions/openshift-tools-installer/releases/tag/v1.11 fixed this issue

**Comment by michaelms-myriad** [comment]
Looks like the issue still resides in v1.12 :

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: redhat-actions/openshift-tools-installer@2de9a80cf012ad0601021515481d433b91ef8fd5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
```
Is someone able to confirm that this is the case?

Thanks!

**Comment by oestoer** [comment]
@michaelms-myriad it's not the same issue. The original was a `node12` deprecation warning, this one is for `node16`.
