### ISSUE TITLE
[BUG] The `set-output` command deprecation warning

### ISSUE THREAD

**Issue by ViacheslavKudinov** [redhat-actions/openshift-tools-installer#89]
### Version

`redhat-actions/openshift-tools-installer@v1`

### Describe the bug

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by anetbnd** [comment]
We are facing the same issue. The migration to actions/core version 1.10.0 is very simply. Is there any timeline, when this will be done for this action?

**Comment by divyansh42** [comment]
Action has been updated, changes should reflect in `v1` and `v1.12`
